In [1]:
import numpy as np
from gsnake.utils import OneHotBox, SnakeGrid, SnakeState, SnakeObservation
from gsnake.configs import GoogleSnakeConfig

In [2]:
config = GoogleSnakeConfig(multi_channel=True, reward_mode='time_constrained', reward_scale=1, n_foods=3)
state = SnakeGrid(config)
state.reset()

In [3]:
obs = SnakeObservation(config.grid_shape, multi_channel=True)

In [4]:
obs.dtype

numpy.uint8

In [5]:
obs.convert(state)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


IndexError: arrays used as indices must be of integer (or boolean) type